name: voro
channels:
  - pytorch
  - ostrokach
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - bottleneck=1.3.7
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2024.7.2
  - certifi=2024.8.30
  - charset-normalizer=3.3.2
  - cuda-cudart=12.1.105
  - cuda-cupti=12.1.105
  - cuda-libraries=12.1.0
  - cuda-nvrtc=12.1.105
  - cuda-nvtx=12.1.105
  - cuda-opencl=12.5.39
  - cuda-runtime=12.1.0
  - cuda-version=12.5
  - dssp=2.2.1
  - ffmpeg=4.3
  - filelock=3.13.1
  - freetype=2.12.1
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.6.15
  - idna=3.7
  - intel-openmp=2023.1.0
  - jinja2=3.1.4
  - jpeg=9e
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libcublas=12.1.0.26
  - libcufft=11.0.2.4
  - libcufile=1.10.1.7
  - libcurand=10.3.6.82
  - libcusolver=11.4.4.55
  - libcusparse=12.0.2.55
  - libdeflate=1.17
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.4
  - libjpeg-turbo=2.0.0
  - libnpp=12.0.2.50
  - libnvjitlink=12.1.105
  - libnvjpeg=12.1.1.14
  - libpng=1.6.39
  - libstdcxx-ng=11.2.0
  - libtasn1=4.19.0
  - libtiff=4.5.1
  - libunistring=0.9.10
  - libwebp-base=1.3.2
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - markupsafe=2.1.3
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.3.0
  - ncurses=6.4
  - nettle=3.7.3
  - networkx=3.2.1
  - numexpr=2.8.7
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openssl=3.0.15
  - pandas=2.2.2
  - pillow=10.4.0
  - pip=24.0
  - pysocks=1.7.1
  - python=3.9.19
  - python-dateutil=2.9.0post0
  - python-tzdata=2023.3
  - pytorch=2.1.0
  - pytorch-cuda=12.1
  - pytorch-mutex=1.0
  - pytz=2024.1
  - pyyaml=6.0.1
  - readline=8.2
  - requests=2.32.3
  - setuptools=69.5.1
  - six=1.16.0
  - sqlite=3.45.3
  - sympy=1.12
  - tbb=2021.8.0
  - tk=8.6.14
  - torchaudio=2.1.0
  - torchtriton=2.1.0
  - torchvision=0.16.0
  - typing_extensions=4.11.0
  - tzdata=2024a
  - urllib3=2.2.2
  - wheel=0.43.0
  - xz=5.4.6
  - yaml=0.2.5
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - aiohttp==3.9.5
      - aiosignal==1.3.1
      - async-timeout==4.0.3
      - attrs==23.2.0
      - biopython==1.84
      - click==8.1.7
      - contourpy==1.2.1
      - cycler==0.12.1
      - docker-pycreds==0.4.0
      - fair-esm==2.0.0
      - fonttools==4.53.1
      - frozenlist==1.4.1
      - fsspec==2024.6.1
      - gitdb==4.0.11
      - gitpython==3.1.43
      - gudhi==3.10.1
      - importlib-resources==6.4.0
      - joblib==1.4.2
      - kiwisolver==1.4.5
      - lightning-utilities==0.11.6
      - multidict==6.0.5
      - packaging==24.1
      - platformdirs==4.2.2
      - protobuf==5.27.2
      - psutil==6.0.0
      - pyg-lib==0.4.0+pt21cu121
      - pyparsing==3.1.2
      - pytorch-lightning==2.3.3
      - scikit-learn==1.5.1
      - scipy==1.13.1
      - sentry-sdk==2.11.0
      - setproctitle==1.3.3
      - smmap==5.0.1
      - threadpoolctl==3.5.0
      - torch-cluster==1.6.3+pt21cu121
      - torch-geometric==2.5.3
      - torch-scatter==2.1.2+pt21cu121
      - torch-sparse==0.6.18+pt21cu121
      - torch-spline-conv==1.2.2+pt21cu121
      - torchmetrics==1.4.0.post0
      - tqdm==4.66.4
      - yarl==1.9.4
      - zipp==3.19.2
      - -f https://data.pyg.org/whl/torch-2.1.0+cu121.html